CREATE TABLE IF NOT EXISTS user (
    id VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS asset_category (
    id VARCHAR(255),
    user_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_asset_category_user FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS asset (
    id VARCHAR(255),
    user_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category_id VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_asset_user FOREIGN KEY (user_id) REFERENCES user(id),
    CONSTRAINT fk_asset_category FOREIGN KEY (category_id) REFERENCES asset_category(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS asset_change (
    id VARCHAR(255),
    user_id VARCHAR(255) NOT NULL,
    asset_id VARCHAR(255) NOT NULL,
    amount INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_asset_change_user FOREIGN KEY (user_id) REFERENCES user(id),
    CONSTRAINT fk_asset_change_asset FOREIGN KEY (asset_id) REFERENCES asset(id)
);

CREATE TABLE IF NOT EXISTS record_type (
    name VARCHAR(32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS record (
    id VARCHAR(255),
    user_id VARCHAR(255) NOT NULL,
    record_type VARCHAR(32) NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES user(id), -- synbolを命名しないとmysqldefがエラーになる
    CONSTRAINT fk_record_type FOREIGN KEY (record_type) REFERENCES record_type(name)
);

CREATE TABLE IF NOT EXISTS tag (
    id VARCHAR(255),
    user_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (user_id, name),
    CONSTRAINT fk_tag_user FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS record_tag (
    record_id VARCHAR(255) NOT NULL,
    tag_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (record_id, tag_id),
    CONSTRAINT fk_record FOREIGN KEY (record_id) REFERENCES record(id),
    CONSTRAINT fk_tag FOREIGN KEY (tag_id) REFERENCES tag(id)
);
