package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"
	"kakeibo-web-server/graph"
)

// Void is the resolver for the void field.
func (r *queryResolver) Void(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Void - void"))
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
